[#164] chore: ci 수정

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -14,7 +14,7 @@ on:
     branches: [ "release", "develop" ]
 
 jobs:
-  ci:
+  ci-api:
     if: |
       (github.event_name == 'push' && github.ref == 'refs/heads/develop') ||
       (github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'develop')
@@ -23,7 +23,7 @@ jobs:
       contents: read
 
     steps:
-      #JDK setting
+
       - uses: actions/checkout@v4
       - name: Set up JDK 17
         uses: actions/setup-java@v4
@@ -31,16 +31,16 @@ jobs:
           java-version: '17'
           distribution: 'temurin'
 
-      # create application-prod.yml
+
       - name: make application-prod.yml
         run: |
-          mkdir -p src/main/resources
-          cd src/main/resources
+          mkdir -p api/src/main/resources
+          cd api/src/main/resources
           touch ./application-prod.yml
           echo "${{secrets.PROPERTIES_PROD}}" > ./application-prod.yml
         shell: bash
 
-      #gradle caching
+
       - name: Gradle Caching
         uses: actions/cache@v3
         with:
@@ -51,130 +51,176 @@ jobs:
             restore-keys: |
             ${{ runner.os }}-gradle-
 
-      #gradle build
+
       - name: Setup Gradle
         uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582
 
-      - name: Build with Gradle Wrapper
+      - name: Build API Module
         run: |
           export SPRING_PROFILES_ACTIVE=prod
-          ./gradlew build -x test 
+          ./gradlew :api:build -x test 
 
-  cd:
+  ci-batch:
     if: |
-      (github.event_name == 'push' && github.ref == 'refs/heads/release') ||
-      (github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'release')
+      (github.event_name == 'push' && github.ref == 'refs/heads/develop') ||
+      (github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'develop')
     runs-on: ubuntu-latest
     permissions:
       contents: read
 
     steps:
+
       - uses: actions/checkout@v4
+      - name: Set up JDK 17
+        uses: actions/setup-java@v4
+        with:
+          java-version: '17'
+          distribution: 'temurin'
 
-      # create application-prod.yml
+
       - name: make application-prod.yml
-
         run: |
-          cd ./src/main/resources
+          mkdir -p batch/src/main/resources
+          cd batch/src/main/resources
           touch ./application-prod.yml
-          echo "${{ secrets.PROPERTIES_PROD}}" > ./application-prod.yml
+          echo "${{secrets.PROPERTIES_PROD}}" > ./application-prod.yml
         shell: bash
 
-      # gradle build
-      - name: gradle build
+
+      - name: Gradle Caching
+        uses: actions/cache@v3
+        with:
+          path: |
+            ~/.gradle/caches
+            ~/.gradle/wrapper
+            key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
+            restore-keys: |
+            ${{ runner.os }}-gradle-
+
+
+      - name: Setup Gradle
+        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582
+
+      - name: Build Batch Module
         run: |
           export SPRING_PROFILES_ACTIVE=prod
-          ./gradlew build -x test
-
-      #docker build&push
-      - name: Docker build & push to prod
-        run: |
-          docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
-          docker build -f Dockerfile -t ${{secrets.DOCKER_USERNAME}}/docker-joonggaemoa .
-          docker push ${{secrets.DOCKER_USERNAME}}/docker-joonggaemoa
-
-      #deploy to ec2
-      - name: Deploy to prod
-        uses: appleboy/ssh-action@master
-        with:
-          host: ${{ secrets.HOST_PROD }}
-          username: ubuntu
-          key: ${{ secrets.PRIVATE_KEY }}
-          script: |
-
-            # 초기 상태 설정
-            DEPLOY_STATUS="success"
-
-            # 컨테이너, 이미지 확인
-            echo "Docker Imformations:"
-            sudo docker ps
-            sudo docker images
-
-            # 기존 컨테이너 ID 조회, 중지
-            OLD_CONTAINER_ID=$(sudo docker ps -aq --filter name=joonggaemoa)
-            sudo docker stop $OLD_CONTAINER_ID 2>/dev/null || true
-            #sudo docker rm $OLD_CONTAINER_ID 2>/dev/null || true
-            
-            # 기존 'new-joonggaemoa' 컨테이너 ID 조회 및 삭제
-            NEW_CONTAINER_ID=$(sudo docker ps -aq --filter name=new-joonggaemoa)
-            if [ -n "$NEW_CONTAINER_ID" ]; then
-              echo "Stopping and removing existing new-joonggaemoa container: $NEW_CONTAINER_ID"
-              sudo docker stop $NEW_CONTAINER_ID 2>/dev/null || true
-              sudo docker rm $NEW_CONTAINER_ID 2>/dev/null || true
-            fi
-            
-            # 새로운 컨테이너 pull, run
-            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/docker-joonggaemoa 
-            sudo docker run -d --name new-joonggaemoa -p 8080:8080 \
-              -e SPRING_PROFILES_ACTIVE=prod \
-              ${{ secrets.DOCKER_USERNAME }}/docker-joonggaemoa 
-            
-            # log 
-            sleep 10
-            sudo docker logs new-joonggaemoa 
-            
-            # 컨테이너 실행 확인
-            if ! sudo docker ps | grep -q new-joonggaemoa; then
-              echo "New Container failed to start"
-              sudo docker rm new-joonggaemoa 2>/dev/null || true
-
-              # 새로운 컨테이너 실행 실패 시, 기존 컨테이너 재시작
-              if [ -n "$OLD_CONTAINER_ID" ]; then
-                DEPLOY_STATUS="failed"
-                echo "Restarting old container: $OLD_CONTAINER_ID"
-                sudo docker start $OLD_CONTAINER_ID 
-            
-                # 기존 컨테이너 재시작 확인
-                sleep 10
-                if sudo docker ps | grep -q "$OLD_CONTAINER_ID"; then
-                  echo "Rollback successful. Old container is running."
-                else
-                  echo "Rollback failed. Old container did not start properly."
-                  exit 1
-                fi
-              else
-                DEPLOY_STATUS="old_failed"
-                echo "No old container found. Rollback not possible."
-                exit 1
-              fi
-            else
-              # 컨테이너, 이미지 정리
-              sudo docker rm $OLD_CONTAINER_ID || exit 1
-              sudo docker rename new-joonggaemoa joonggaemoa || exit 1
-              sudo docker image prune -f 2>/dev/null || true
-            fi
-
-            echo "After Deploy:"
-            sudo docker ps
-            sudo docker images
-
-            echo "Deploy Status: $DEPLOY_STATUS"
-            if [ "$DEPLOY_STATUS" == "failed" ]; then
-              echo "New deploy failed. Please check the logs."
-              exit 1
-            elif [ "$DEPLOY_STATUS" == "old_failed" ]; then
-              echo "Rollback failed. Please check the logs."
-              exit 1
-            fi
+          ./gradlew :batch:build -x test 
+          
+          #  cd:
+          #    if: |
+          #      (github.event_name == 'push' && github.ref == 'refs/heads/release') ||
+          #      (github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'release')
+          #    runs-on: ubuntu-latest
+          #    permissions:
+          #      contents: read
+          #
+          #    steps:
+          #      - uses: actions/checkout@v4
+          #
+          #      # create application-prod.yml
+          #      - name: make application-prod.yml
+          #
+          #        run: |
+          #          cd ./src/main/resources
+          #          touch ./application-prod.yml
+          #          echo "${{ secrets.PROPERTIES_PROD}}" > ./application-prod.yml
+          #        shell: bash
+          #
+          #      # gradle build
+          #      - name: gradle build
+          #        run: |
+          #          export SPRING_PROFILES_ACTIVE=prod
+          #          ./gradlew build -x test
+          #
+          #      #docker build&push
+          #      - name: Docker build & push to prod
+          #        run: |
+          #          docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
+          #          docker build -f Dockerfile -t ${{secrets.DOCKER_USERNAME}}/docker-joonggaemoa .
+          #          docker push ${{secrets.DOCKER_USERNAME}}/docker-joonggaemoa
+          #
+          #      #deploy to ec2
+          #      - name: Deploy to prod
+          #        uses: appleboy/ssh-action@master
+          #        with:
+          #          host: ${{ secrets.HOST_PROD }}
+          #          username: ubuntu
+          #          key: ${{ secrets.PRIVATE_KEY }}
+          #          script: |
+          #
+          #            # 초기 상태 설정
+          #            DEPLOY_STATUS="success"
+          #
+          #            # 컨테이너, 이미지 확인
+          #            echo "Docker Imformations:"
+          #            sudo docker ps
+          #            sudo docker images
+          #
+          #            # 기존 컨테이너 ID 조회, 중지
+          #            OLD_CONTAINER_ID=$(sudo docker ps -aq --filter name=joonggaemoa)
+          #            sudo docker stop $OLD_CONTAINER_ID 2>/dev/null || true
+          #            #sudo docker rm $OLD_CONTAINER_ID 2>/dev/null || true
+          #
+          #            # 기존 'new-joonggaemoa' 컨테이너 ID 조회 및 삭제
+          #            NEW_CONTAINER_ID=$(sudo docker ps -aq --filter name=new-joonggaemoa)
+          #            if [ -n "$NEW_CONTAINER_ID" ]; then
+          #              echo "Stopping and removing existing new-joonggaemoa container: $NEW_CONTAINER_ID"
+          #              sudo docker stop $NEW_CONTAINER_ID 2>/dev/null || true
+          #              sudo docker rm $NEW_CONTAINER_ID 2>/dev/null || true
+          #            fi
+          #
+          #            # 새로운 컨테이너 pull, run
+          #            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/docker-joonggaemoa
+          #            sudo docker run -d --name new-joonggaemoa -p 8080:8080 \
+          #              -e SPRING_PROFILES_ACTIVE=prod \
+          #              ${{ secrets.DOCKER_USERNAME }}/docker-joonggaemoa
+          #
+          #            # log
+          #            sleep 10
+          #            sudo docker logs new-joonggaemoa
+          #
+          #            # 컨테이너 실행 확인
+          #            if ! sudo docker ps | grep -q new-joonggaemoa; then
+          #              echo "New Container failed to start"
+          #              sudo docker rm new-joonggaemoa 2>/dev/null || true
+          #
+          #              # 새로운 컨테이너 실행 실패 시, 기존 컨테이너 재시작
+          #              if [ -n "$OLD_CONTAINER_ID" ]; then
+          #                DEPLOY_STATUS="failed"
+          #                echo "Restarting old container: $OLD_CONTAINER_ID"
+          #                sudo docker start $OLD_CONTAINER_ID
+          #
+          #                # 기존 컨테이너 재시작 확인
+          #                sleep 10
+          #                if sudo docker ps | grep -q "$OLD_CONTAINER_ID"; then
+          #                  echo "Rollback successful. Old container is running."
+          #                else
+          #                  echo "Rollback failed. Old container did not start properly."
+          #                  exit 1
+          #                fi
+          #              else
+          #                DEPLOY_STATUS="old_failed"
+          #                echo "No old container found. Rollback not possible."
+          #                exit 1
+          #              fi
+          #            else
+          #              # 컨테이너, 이미지 정리
+          #              sudo docker rm $OLD_CONTAINER_ID || exit 1
+          #              sudo docker rename new-joonggaemoa joonggaemoa || exit 1
+          #              sudo docker image prune -f 2>/dev/null || true
+          #            fi
+          #
+          #            echo "After Deploy:"
+          #            sudo docker ps
+          #            sudo docker images
+          #
+          #            echo "Deploy Status: $DEPLOY_STATUS"
+          #            if [ "$DEPLOY_STATUS" == "failed" ]; then
+          #              echo "New deploy failed. Please check the logs."
+          #              exit 1
+          #            elif [ "$DEPLOY_STATUS" == "old_failed" ]; then
+          #              echo "Rollback failed. Please check the logs."
+          #              exit 1
+          #            fi
             
             
